# Generated by Django 3.0.2 on 2020-01-05 23:45

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_audience_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=core.models.advertising_image_file_path)),
                ('fromDate', models.DateTimeField(auto_now_add=True)),
                ('toDate', models.DateTimeField(auto_now_add=True)),
                ('seconds', models.IntegerField(default=0)),
                ('audiences', models.ManyToManyField(to='core.Audience')),
                ('devices', models.ManyToManyField(to='core.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
