# Generated by Django 3.0.2 on 2020-01-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
