# Generated by Django 3.0.2 on 2020-03-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200110_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='fromDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
